name: bot-fy
services:
   bot-fy:
      container_name: bot-fy
      image: bot-fy
      env_file:
        - .env
      build: 
          dockerfile: Dockerfile
      restart: always
      environment:
          - TZ=America/Sao_Paulo
      deploy:
          resources:
              limits:
                  memory: 1G